# this model was generated by ai, primarily because I didn't want to write all the definitions by hand

from app.models.base import Base
from sqlalchemy.orm import Mapped, mapped_column # type: ignore
from sqlalchemy import ForeignKey # type: ignore

class MatchParticipant(Base):
    __tablename__ = "match_participants"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    match_id: Mapped[str] = mapped_column(ForeignKey("matches.match_id"))
    puuid: Mapped[str] = mapped_column(ForeignKey("players.puuid"))
    participant_id: Mapped[int]  # 1-10, links to timeline frames
    champion_id: Mapped[int]
    champion_name: Mapped[str]
    team_id: Mapped[int]  # 100 or 200
    individual_position: Mapped[str | None]
    team_position: Mapped[str | None]
    win: Mapped[bool]

    # End-of-game stats
    kills: Mapped[int | None]
    deaths: Mapped[int | None]
    assists: Mapped[int | None]
    cs_total: Mapped[int | None]
    cs_per_min: Mapped[float | None]
    vision_score: Mapped[int | None]
    wards_placed: Mapped[int | None]
    wards_killed: Mapped[int | None]
    control_wards: Mapped[int | None]
    gold_earned: Mapped[int | None]
    gold_spent: Mapped[int | None]
    damage_to_champions: Mapped[int | None]
    damage_taken: Mapped[int | None]
    kill_participation: Mapped[float | None]
    kda: Mapped[float | None]
    gold_per_min: Mapped[float | None]
    damage_per_min: Mapped[float | None]
    lane_cs_at_10: Mapped[int | None]