# this model was generated by ai, primarily because I didn't want to write all the definitions by hand

from app.models.base import Base
from sqlalchemy.orm import Mapped, mapped_column # type: ignore
from sqlalchemy import ForeignKey, UniqueConstraint # type: ignore

class TimelineFrame(Base):
    __tablename__ = "timeline_frames"
    __table_args__ = (
        UniqueConstraint('match_id', 'participant_id', 'timestamp_min'),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    match_id: Mapped[str] = mapped_column(ForeignKey("matches.match_id"))
    participant_id: Mapped[int]  # 1-10, joins to match_participants
    timestamp_min: Mapped[int]   # minute mark: 1, 2, 3...

    # Gold
    current_gold: Mapped[int | None]
    total_gold: Mapped[int | None]
    gold_per_second: Mapped[int | None]

    # CS
    minions_killed: Mapped[int | None]
    jungle_minions_killed: Mapped[int | None]

    # Progression
    level: Mapped[int | None]
    xp: Mapped[int | None]
    time_enemy_spent_controlled: Mapped[int | None]

    # Position (for heatmaps)
    pos_x: Mapped[int | None]
    pos_y: Mapped[int | None]

    # Damage (cumulative at this frame)
    physical_damage_to_champs: Mapped[int | None]
    magic_damage_to_champs: Mapped[int | None]
    total_damage_to_champs: Mapped[int | None]
    total_damage_taken: Mapped[int | None]