"""remove players foreign key

Revision ID: 6d3ac004a8b4
Revises: 93b08c97f716
Create Date: 2026-05-24 16:37:27.902735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3ac004a8b4'
down_revision: Union[str, Sequence[str], None] = '93b08c97f716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('match_participants_puuid_fkey'), 'match_participants', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('match_participants_puuid_fkey'), 'match_participants', 'players', ['puuid'], ['puuid'])
    # ### end Alembic commands ###
