"""add unique constraints

Revision ID: 93b08c97f716
Revises: f3c09bdb91e7
Create Date: 2026-05-24 14:36:19.763219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b08c97f716'
down_revision: Union[str, Sequence[str], None] = 'f3c09bdb91e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match_participants', ['match_id', 'participant_id'])
    op.create_unique_constraint(None, 'timeline_frames', ['match_id', 'participant_id', 'timestamp_min'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline_frames', type_='unique')
    op.drop_constraint(None, 'match_participants', type_='unique')
    # ### end Alembic commands ###
