"""initial schema

Revision ID: f3c09bdb91e7
Revises: 
Create Date: 2026-05-24 10:25:28.809537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c09bdb91e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_start', sa.DateTime(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_version', sa.String(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=False),
    sa.Column('tag_line', sa.String(length=64), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('individual_position', sa.String(), nullable=True),
    sa.Column('team_position', sa.String(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('cs_total', sa.Integer(), nullable=True),
    sa.Column('cs_per_min', sa.Float(), nullable=True),
    sa.Column('vision_score', sa.Integer(), nullable=True),
    sa.Column('wards_placed', sa.Integer(), nullable=True),
    sa.Column('wards_killed', sa.Integer(), nullable=True),
    sa.Column('control_wards', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('gold_spent', sa.Integer(), nullable=True),
    sa.Column('damage_to_champions', sa.Integer(), nullable=True),
    sa.Column('damage_taken', sa.Integer(), nullable=True),
    sa.Column('kill_participation', sa.Float(), nullable=True),
    sa.Column('kda', sa.Float(), nullable=True),
    sa.Column('gold_per_min', sa.Float(), nullable=True),
    sa.Column('damage_per_min', sa.Float(), nullable=True),
    sa.Column('lane_cs_at_10', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_frames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_min', sa.Integer(), nullable=False),
    sa.Column('current_gold', sa.Integer(), nullable=True),
    sa.Column('total_gold', sa.Integer(), nullable=True),
    sa.Column('gold_per_second', sa.Integer(), nullable=True),
    sa.Column('minions_killed', sa.Integer(), nullable=True),
    sa.Column('jungle_minions_killed', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('time_enemy_spent_controlled', sa.Integer(), nullable=True),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('physical_damage_to_champs', sa.Integer(), nullable=True),
    sa.Column('magic_damage_to_champs', sa.Integer(), nullable=True),
    sa.Column('total_damage_to_champs', sa.Integer(), nullable=True),
    sa.Column('total_damage_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_frames')
    op.drop_table('match_participants')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
